#!/bin/sh

DAEMON=/usr/bin/etcd2
CONFIG=/etc/etcd2.conf

[ -x $DAEMON ] || exit 0
[ -f $CONFIG ] || exit 0

source $CONFIG

case "$1" in
	start)
		printf "Starting etcd daemon: "
		[ -n $ETCD_DATA_DIR ] || [ -d $ETCD_DATA_DIR ] || mkdir -p $ETCD_DATA_DIR
		start-stop-daemon -S -x $DAEMON
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping etcd daemon: "
		start-stop-daemon -K -x $DAEMON
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload|force-reload)
		$0 stop || true
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}"
		exit 1
esac

exit 0
